import { TableRow } from '@/store/types';

export const sampleData: TableRow[] = [
  { id: '1', name: 'John Doe', email: 'john.doe@example.com', age: 32, role: 'Developer' },
  { id: '2', name: 'Jane Smith', email: 'jane.smith@example.com', age: 28, role: 'Designer' },
  { id: '3', name: 'Robert Johnson', email: 'robert.j@example.com', age: 45, role: 'Manager' },
  { id: '4', name: 'Emily Davis', email: 'emily.davis@example.com', age: 35, role: 'Analyst' },
  { id: '5', name: 'Michael Wilson', email: 'michael.w@example.com', age: 41, role: 'Developer' },
  { id: '6', name: 'Sarah Brown', email: 'sarah.brown@example.com', age: 29, role: 'Designer' },
  { id: '7', name: 'David Taylor', email: 'david.taylor@example.com', age: 38, role: 'Manager' },
  { id: '8', name: 'Jennifer Martinez', email: 'jennifer.m@example.com', age: 26, role: 'Developer' },
  { id: '9', name: 'Christopher Anderson', email: 'chris.a@example.com', age: 44, role: 'Analyst' },
  { id: '10', name: 'Amanda Thomas', email: 'amanda.t@example.com', age: 31, role: 'Designer' },
  { id: '11', name: 'James Jackson', email: 'james.jackson@example.com', age: 39, role: 'Developer' },
  { id: '12', name: 'Jessica White', email: 'jessica.white@example.com', age: 27, role: 'Manager' },
  { id: '13', name: 'Daniel Harris', email: 'daniel.harris@example.com', age: 42, role: 'Analyst' },
  { id: '14', name: 'Ashley Clark', email: 'ashley.clark@example.com', age: 30, role: 'Designer' },
  { id: '15', name: 'Matthew Rodriguez', email: 'matthew.r@example.com', age: 36, role: 'Developer' },
  { id: '16', name: 'Brittany Lewis', email: 'brittany.l@example.com', age: 33, role: 'Manager' },
  { id: '17', name: 'Andrew Lee', email: 'andrew.lee@example.com', age: 40, role: 'Analyst' },
  { id: '18', name: 'Samantha Hall', email: 'samantha.hall@example.com', age: 25, role: 'Developer' },
  { id: '19', name: 'Joshua Allen', email: 'joshua.allen@example.com', age: 47, role: 'Designer' },
  { id: '20', name: 'Megan Young', email: 'megan.young@example.com', age: 34, role: 'Manager' },
  { id: '21', name: 'Ryan Hernandez', email: 'ryan.hernandez@example.com', age: 37, role: 'Developer' },
  { id: '22', name: 'Lauren King', email: 'lauren.king@example.com', age: 29, role: 'Analyst' },
  { id: '23', name: 'Kevin Wright', email: 'kevin.wright@example.com', age: 43, role: 'Manager' },
  { id: '24', name: 'Nicole Lopez', email: 'nicole.lopez@example.com', age: 26, role: 'Designer' },
  { id: '25', name: 'Brandon Hill', email: 'brandon.hill@example.com', age: 38, role: 'Developer' },
];